# Generated by Django 3.0.6 on 2020-06-02 09:02

import BiometricAuth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BiometricAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintimages',
            name='fingerprint_image',
            field=models.ImageField(default='', upload_to=BiometricAuth.models.fingerprint_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fingerprintimages',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_image', to='BiometricAuth.UserBiometry'),
            preserve_default=False,
        ),
    ]
